# A makefile
CXX = clang++
CFLAGS = --std=c++11 -Wall -Wextra -g

default: main

debug: CFLAGS += -DDEBUG
debug: default 

main: main.cpp fsImple.o dirEntry.o inode.o
	$(CXX) $(CFLAGS) -o main main.cpp dirEntry.o fsImple.o inode.o

fsImple.o: fsImple.cpp fsImple.hpp
	$(CXX) $(CFLAGS) -c fsImple.cpp

dirEntry.o: dirEntry.cpp dirEntry.hpp
	$(CXX) $(CFLAGS) -c dirEntry.cpp

inode.o: inode.cpp inode.hpp
	$(CXX) $(CFLAGS) -c inode.cpp

clean:
	@rm -rf main *.o
